from backend.app.models import Clip


def clip(
    clip_id: str,
    title: str,
    seconds: int,
    description: str,
    tags: list[str],
    confidence: float,
) -> Clip:
    minutes, remainder = divmod(seconds, 60)
    return Clip(
        id=clip_id,
        videoId="demo-index",
        title=title,
        thumbnail="",
        timestamp=f"{minutes:02d}:{remainder:02d}",
        seconds=seconds,
        description=description,
        tags=tags,
        confidence=confidence,
        sourceLabel="Demo index - not a verified YouTube source",
        sourceUrl=None,
    )


DEMO_CLIPS = [
    clip(
        "cat-run-1",
        "Cat sprinting across room",
        21,
        "A black and white cat runs quickly across a bright room, good for a playful chase or escape moment.",
        ["cat", "running", "sprint", "fast", "indoor"],
        0.98,
    ),
    clip(
        "cat-run-2",
        "Cat sudden run reaction",
        9,
        "A cat suddenly starts running after reacting to something off camera, useful for quick comedy edits.",
        ["cat", "running", "reaction", "funny", "fast"],
        0.96,
    ),
    clip(
        "cat-run-3",
        "Cat running down hallway",
        42,
        "A cat runs straight through a hallway with clear forward motion and a clean timestamped action beat.",
        ["cat", "running", "hallway", "motion", "chase"],
        0.95,
    ),
    clip(
        "cat-run-4",
        "Kitten running on floor",
        64,
        "A small kitten runs across the floor in a short energetic burst.",
        ["cat", "kitten", "running", "cute", "floor"],
        0.93,
    ),
    clip(
        "cat-run-5",
        "Cat running outside",
        88,
        "An outdoor cat runs through open space with natural daylight and visible full-body movement.",
        ["cat", "running", "outdoor", "daylight", "animal"],
        0.92,
    ),
    clip(
        "cat-run-6",
        "Cat chase in living room",
        117,
        "A cat darts around furniture in a living room, matching searches for cat running or cat chasing.",
        ["cat", "running", "chase", "living-room", "funny"],
        0.91,
    ),
    clip(
        "cat-run-7",
        "Fast cat jump and run",
        31,
        "A cat jumps, lands, and runs away in one quick sequence.",
        ["cat", "running", "jump", "escape", "fast"],
        0.9,
    ),
    clip(
        "cat-run-8",
        "Cat running toward camera",
        53,
        "A cat runs toward the camera, giving a clear front-facing animal motion shot.",
        ["cat", "running", "toward-camera", "animal", "motion"],
        0.89,
    ),
    clip(
        "cat-run-9",
        "Cat sprinting outdoors",
        101,
        "A cat sprints outside through an open area with clear daylight and fast animal movement.",
        ["cat", "running", "sprint", "outdoor", "fast"],
        0.88,
    ),
    clip(
        "cat-run-10",
        "Cat running after toy",
        133,
        "A cat runs after a toy across the floor, matching playful cat running searches.",
        ["cat", "running", "toy", "playful", "floor"],
        0.87,
    ),
    clip(
        "cat-run-11",
        "Cat chase across kitchen",
        152,
        "A cat runs quickly across a kitchen during a chase-like moment.",
        ["cat", "running", "chase", "kitchen", "fast"],
        0.86,
    ),
    clip(
        "cat-run-12",
        "Cat zooming through doorway",
        166,
        "A cat zooms through a doorway at high speed, useful for a sudden running insert.",
        ["cat", "running", "doorway", "zoom", "fast"],
        0.85,
    ),
    clip(
        "dog-run-1",
        "Dog chasing person on sidewalk",
        18,
        "A person runs along a sidewalk while a dog chases behind, creating a clear chase scene.",
        ["dog", "running", "chase", "person", "street"],
        0.97,
    ),
    clip(
        "dog-run-2",
        "Dog running through park",
        75,
        "A dog runs through an open park in daylight with fast full-body motion.",
        ["dog", "running", "park", "outdoor", "fast"],
        0.91,
    ),
    clip(
        "rain-street-1",
        "Quiet rainy street",
        78,
        "A moody street scene with wet pavement, soft reflections, and slow cinematic movement.",
        ["rain", "street", "moody", "cinematic", "night"],
        0.93,
    ),
    clip(
        "crowd-cheer-1",
        "Crowd celebration",
        124,
        "A crowd cheers with raised hands and energetic movement, ideal for a victory or hype moment.",
        ["crowd", "cheering", "celebration", "energy"],
        0.9,
    ),
    clip(
        "car-night-1",
        "Night driving cutaway",
        47,
        "A moving vehicle shot with strong contrast and city-light motion, matching a tense travel beat.",
        ["car", "night", "driving", "tense", "motion"],
        0.89,
    ),
    clip(
        "hand-key-1",
        "Close-up hand insert",
        34,
        "A tight close-up insert with hand movement, useful for searches like turning a key or picking up an object.",
        ["close-up", "hand", "key", "insert", "detail"],
        0.86,
    ),
]


SUGGESTIONS = [
    "cat running",
    "cat running down hallway",
    "cat running toward camera",
    "cat running after toy",
    "dog chasing person",
    "running from dog",
    "crowd cheering",
    "quiet rainy street",
    "car driving at night",
    "close up of hand turning key",
    "person running through street",
    "funny animal reaction",
]
